export const MOCK_NEWS = [
  {
    id: '1',
    title: 'Global Markets Rally as Tech Giants Announce Breakthrough Innovations',
    description: 'A detailed look into the latest developments shaping the future of global finance and technology, with exclusive insights from industry leaders.',
    category: 'Finance',
    image: 'https://images.unsplash.com/photo-1611974714024-462cd297c8aa?q=80&w=2070&auto=format&fit=crop',
    author: 'John Doe',
    publishedAt: '2024-10-26T10:00:00Z',
    url: '#',
    isHero: true,
  },
  {
    id: '2',
    title: 'SpaceX Successfully Launches New Satellite Constellation',
    description: 'Expanding global internet coverage with the latest Starlink deployment.',
    category: 'Technology',
    image: 'https://images.unsplash.com/photo-1517976487492-5750f3195933?q=80&w=2070&auto=format&fit=crop',
    author: 'Jane Smith',
    publishedAt: '2024-10-25T14:30:00Z',
    url: '#',
  },
  {
    id: '3',
    title: 'Financial Corporate r: Tech Financial Capture and Financial News',
    description: 'A deep dive into the latest financial trends and corporate strategies.',
    category: 'Finance',
    image: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=2048&auto=format&fit=crop',
    author: 'Alice Johnson',
    publishedAt: '2024-10-25T09:00:00Z',
    url: '#',
  },
  {
    id: '4',
    title: 'Future Exploration is Science beading industry Project technology',
    description: 'How new discoveries are shaping the future of space exploration.',
    category: 'Science',
    image: 'https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?q=80&w=2072&auto=format&fit=crop',
    author: 'Bob Wilson',
    publishedAt: '2024-10-25T08:00:00Z',
    url: '#',
  },
  {
    id: '5',
    title: 'New Screens from Tech Lines Matters for its Financial',
    description: 'The impact of display technology on the financial sector.',
    category: 'Finance',
    image: 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?q=80&w=2070&auto=format&fit=crop',
    author: 'Charlie Brown',
    publishedAt: '2024-10-25T07:00:00Z',
    url: '#',
  },
  {
    id: '6',
    title: "The World's Empower Financial Interes in a Space Innovation",
    description: 'Global interest in space-based financial systems is growing.',
    category: 'Science',
    image: 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=2072&auto=format&fit=crop',
    author: 'David Miller',
    publishedAt: '2024-10-25T06:00:00Z',
    url: '#',
  }
];
